#!/bin/bash

#do this if you want to clone from the repo

if [ $# -eq 0 ]
then
	version=v2.2 #latest stable release
else
	version=$1 #alternate user-def release...latest is prev3-develop
fi

git clone -b $version https://github.com/cburstedde/p4est  p4est_$version

cd p4est_$version
git submodule init
git submodule update
./bootstrap
git branch
tar --exclude='./.git' --exclude='./sc/.git' -cjf ../p4est_$version.tar.bj *
cd ..
rm -rf p4est_$version
